version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'UTC'
      WEBPASSWORD: '${PIHOLE_PASSWORD}'
      SERVERIP: '${SERVER_IP}'
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - pihole-network

  trojan:
    container_name: trojan
    image: trojangfw/trojan:latest
    ports:
      - "443:443/tcp"
    volumes:
      - './trojan/config.json:/config/config.json:ro'
      - './trojan/certs:/certs:ro'
    dns:
      - pihole
      - 1.1.1.1  # Fallback DNS
    restart: unless-stopped
    networks:
      - pihole-network
    depends_on:
      - pihole

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - './nextcloud-db:/var/lib/mysql'
    networks:
      - pihole-network

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    ports:
      - "8080:80/tcp"
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: nextcloud-db
      NEXTCLOUD_ADMIN_USER: '${NEXTCLOUD_ADMIN_USER}'
      NEXTCLOUD_ADMIN_PASSWORD: '${NEXTCLOUD_ADMIN_PASSWORD}'
    volumes:
      - './nextcloud-data:/var/www/html'
      - './nextcloud-config:/var/www/html/config'
    dns:
      - pihole
      - 1.1.1.1
    networks:
      - pihole-network
    depends_on:
      - nextcloud-db
      - pihole

networks:
  pihole-network:
    driver: bridge